/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Javier Ignacio Parraguirre Lizarraga 20/10/23
 */
public class Impresion2 extends javax.swing.JFrame {

    /**
     * Creates new form Impresion2
     */
    public Impresion2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imp2 = new javax.swing.JPanel();
        tabla = new javax.swing.JScrollPane();
        items3tbl = new javax.swing.JTable();
        lbli1 = new javax.swing.JLabel();
        lbli3 = new javax.swing.JLabel();
        lbli2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imp2.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setViewportView(items3tbl);

        lbli1.setBackground(new java.awt.Color(255, 255, 255));
        lbli1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbli1.setForeground(new java.awt.Color(0, 0, 0));
        lbli1.setText(" ");

        lbli3.setBackground(new java.awt.Color(255, 255, 255));
        lbli3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbli3.setForeground(new java.awt.Color(0, 0, 0));
        lbli3.setText(" ");

        lbli2.setBackground(new java.awt.Color(255, 255, 255));
        lbli2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbli2.setForeground(new java.awt.Color(0, 0, 0));
        lbli2.setText(" ");

        javax.swing.GroupLayout imp2Layout = new javax.swing.GroupLayout(imp2);
        imp2.setLayout(imp2Layout);
        imp2Layout.setHorizontalGroup(
            imp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imp2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(imp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(imp2Layout.createSequentialGroup()
                        .addComponent(lbli2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(lbli3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imp2Layout.createSequentialGroup()
                        .addComponent(lbli1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 235, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(imp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imp2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        imp2Layout.setVerticalGroup(
            imp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imp2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbli1)
                .addGap(18, 18, 18)
                .addGroup(imp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbli3)
                    .addComponent(lbli2))
                .addContainerGap(446, Short.MAX_VALUE))
            .addGroup(imp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imp2Layout.createSequentialGroup()
                    .addContainerGap(140, Short.MAX_VALUE)
                    .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impresion2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel imp2;
    protected javax.swing.JTable items3tbl;
    protected javax.swing.JLabel lbli1;
    protected javax.swing.JLabel lbli2;
    protected javax.swing.JLabel lbli3;
    protected javax.swing.JScrollPane tabla;
    // End of variables declaration//GEN-END:variables
}
