package Vistas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import live.store.Cliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



/**
 *
 * @author Javier Ignacio Parraguirre Lizarraga 20/10/23
 */
public class Impresion extends javax.swing.JFrame {

        public JPanel impresion;

    /**
     * Creates new form Impresion
     */
    public Impresion() {
        initComponents();
    }

    Impresion(Cliente cli) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Envio = new javax.swing.JPanel();
        nombretxt = new javax.swing.JTextField();
        ruttxt = new javax.swing.JTextField();
        telefonotxt = new javax.swing.JTextField();
        direcciontxt = new javax.swing.JTextField();
        nombrelbl = new javax.swing.JLabel();
        rutlbl = new javax.swing.JLabel();
        telefonolbl = new javax.swing.JLabel();
        direccionlbl = new javax.swing.JLabel();
        imprimirbtn = new javax.swing.JButton();
        correotxt = new javax.swing.JTextField();
        correolbl = new javax.swing.JLabel();

        setResizable(false);
        setSize(new java.awt.Dimension(755, 566));

        Envio.setBackground(new java.awt.Color(255, 255, 255));
        Envio.setForeground(new java.awt.Color(255, 255, 255));
        Envio.setMaximumSize(new java.awt.Dimension(266, 378));
        Envio.setName(""); // NOI18N
        Envio.setOpaque(false);
        Envio.setPreferredSize(new java.awt.Dimension(266, 378));

        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });

        ruttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruttxtActionPerformed(evt);
            }
        });

        telefonotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonotxtActionPerformed(evt);
            }
        });

        nombrelbl.setText("Nombre:");

        rutlbl.setText("RUT:");

        telefonolbl.setText("Telefono:");

        direccionlbl.setText("Direccion:");

        imprimirbtn.setText("Imprimir");
        imprimirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirbtnActionPerformed(evt);
            }
        });

        correotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correotxtActionPerformed(evt);
            }
        });

        correolbl.setText("Correo:");

        javax.swing.GroupLayout EnvioLayout = new javax.swing.GroupLayout(Envio);
        Envio.setLayout(EnvioLayout);
        EnvioLayout.setHorizontalGroup(
            EnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefonolbl)
                    .addComponent(rutlbl)
                    .addComponent(nombrelbl)
                    .addComponent(correolbl)
                    .addGroup(EnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(EnvioLayout.createSequentialGroup()
                            .addComponent(direccionlbl)
                            .addGap(298, 298, 298))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imprimirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombretxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                .addComponent(ruttxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(telefonotxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(correotxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(direcciontxt, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EnvioLayout.setVerticalGroup(
            EnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombrelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rutlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(telefonolbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correolbl)
                .addGap(2, 2, 2)
                .addComponent(correotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(direccionlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direcciontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Envio.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ruttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruttxtActionPerformed

    private void telefonotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonotxtActionPerformed

    private void imprimirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirbtnActionPerformed
        // TODO add your handling code here:
          imprimirbtn.setVisible(false);
        printRecord();
        this.setVisible(false);
    }//GEN-LAST:event_imprimirbtnActionPerformed

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void correotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correotxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Impresion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Envio;
    private javax.swing.JLabel correolbl;
    public javax.swing.JTextField correotxt;
    private javax.swing.JLabel direccionlbl;
    public javax.swing.JTextField direcciontxt;
    private javax.swing.JButton imprimirbtn;
    private javax.swing.JLabel nombrelbl;
    public javax.swing.JTextField nombretxt;
    private javax.swing.JLabel rutlbl;
    public javax.swing.JTextField ruttxt;
    private javax.swing.JLabel telefonolbl;
    public javax.swing.JTextField telefonotxt;
    // End of variables declaration//GEN-END:variables

    private void printRecord() {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("PDF");

        printerJob.setPrintable(new Printable() {
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex){
                if (pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2d = (Graphics2D)graphics;
                
                graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                
                Envio.paint(graphics2d);
                
                return Printable.PAGE_EXISTS;
            }
        });
        
        boolean returningResult = printerJob.printDialog();
        
        if(returningResult){
            try{
                printerJob.print();
            }catch (PrinterException e){
                JOptionPane.showMessageDialog(this, "Print Error: "+e);
            }
        }
    }
    }

